apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../infrastructure/polyfea
  - ../../../infrastructure/fluxcd
  - ../../../infrastructure/envoy-gateway
  - github.com/metallb/metallb/config/native?ref=v0.14.9
  - metallb-config.yaml

components:
  - ../../../components/version-developers
