apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../infrastructure/polyfea
  - ../../../infrastructure/fluxcd
  - ../../../infrastructure/envoy-gateway

components:
  - ../../../components/version-developers
  - https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml
  - metallb-config.yaml
