apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcastven-xkilian-project-webapi
spec:
  template:
    spec:
      containers:
        - name: xcastven-xkilian-project-webapi-container
          env:
            - name: WAC_MONGO_HOST
              value: null
              valueFrom:
                configMapKeyRef:
                  name: mongodb-connection
                  key: host
            - name: WAC_MONGO_PORT
              value: null
              valueFrom:
                configMapKeyRef:
                  name: mongodb-connection
                  key: port
            - name: WAC_MONGO_USER
              value: null
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: username
            - name: WAC_MONGO_PASSWORD
              value: null
              valueFrom:
                secretKeyRef:
                  name: mongodb-auth
                  key: password
