apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: xcastven-xkilian-cd # v spoločnom klastri je nasadených viacero takýchto objektov
  namespace: wac-hospital
spec:
  wait: true
  interval: 42s
  path: gitops/clusters/wac-aks
  prune: true
  sourceRef:
    kind: GitRepository
    name: xcastven-xkilian-gitops-repo
