apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace:
  wac-hospital # chceme tieto objekty umiestniť do `wac-hospital` namespace
  # tento zapis preťaží hodnoty "namespace" vo všetkých objektoch
labels:
  - pairs:
      app.kubernetes.io/part-of: wac-hospital

resources:
  - ../../../apps/xcastven-xkilian-project
  - ../../../apps/xcastven-xkilian-project-webapi

patches:
  - path: patches/webapi.service.yaml

components:
  - ../../../components/version-developers
  - "https://github.com/Nesquiko/xcastven-xkilian-wac-project//backend/deployments/kustomize/components/mongodb" # ?ref=v1.0.1
