apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcastven-xkilian-project
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: xcastven-xkilian-project-label
  template:
    metadata:
      labels:
        pod: xcastven-xkilian-project-label
    spec:
      containers:
        - name: xcastven-xkilian-wac-fe
          image: nesquiko/xcastven-xkilian-wac-fe
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: "32M"
              cpu: "0.1"
            limits:
              memory: "320M"
              cpu: "0.3"
