kind: Service
apiVersion: v1
metadata:
  name: xcastven-xkilian-project
spec:
  selector:
    pod: xcastven-xkilian-project-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
