apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xcastven-xkilian-project-content
spec:
  microFrontend: xcastven-xkilian-project
  element: xcastven-xkilian-project-home-page
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^(\\.?/)?xcastven-xkilian-project(/.*)?$"
