apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-repo
  namespace: wac-hospital
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: repository-pat
  timeout: 1m0s
  url: https://github.com/Nesquiko/xcastven-xkilian-wac-project
