apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcastven-xkilian-project-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: xcastven-xkilian-project-webapi-label
  template:
    metadata:
      labels:
        pod: xcastven-xkilian-project-webapi-label
    spec:
      containers:
        - name: xcastven-xkilian-project-webapi-container
          image: nesquiko/xcastven-xkilian-wac-be:latest
          imagePullPolicy: Always
          ports:
            - name: webapi-port
              containerPort: 8080
          env:
            - name: WAC_LOG_LEVEL
              value: "0"
            - name: WAC_APP_TIMEZONE
              value: "Europe/Bratislava"
            - name: WAC_APP_HOST
              value: "0.0.0.0"
            - name: WAC_APP_PORT
              value: "8080"
            - name: WAC_MONGO_HOST
              value: mongodb
            - name: WAC_MONGO_PORT
              value: "27017"
              # change to actual value
            - name: WAC_MONGO_USER
              value: ""
              #change to actual value
            - name: WAC_MONGO_PASSWORD
              value: ""
            - name: WAC_MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: xcastven-xkilian-project-webapi-config
                  key: database
          resources:
            requests:
              memory: "64Mi"
              cpu: "0.01"
            limits:
              memory: "512Mi"
              cpu: "0.3"
        - name: openapi-ui
          image: swaggerapi/swagger-ui
          imagePullPolicy: Always
          ports:
            - name: api-ui
              containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: URL
              value: /openapi
            - name: BASE_URL
              value: /openapi-ui
            - name: FILTER
              value: "true"
            - name: DISPLAY_OPERATION_ID
              value: "true"
          resources:
            requests:
              memory: "16M"
              cpu: "0.01"
            limits:
              memory: "64M"
              cpu: "0.1"
