kind: Service
apiVersion: v1
metadata:
  name: xcastven-xkilian-project-webapi
spec:
  selector:
    pod: xcastven-xkilian-project-webapi-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: webapi-port
