/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AmbulanceApp {
    }
    interface AppointmentScheduler {
    }
    interface HomePage {
    }
}
declare global {
    interface HTMLAmbulanceAppElement extends Components.AmbulanceApp, HTMLStencilElement {
    }
    var HTMLAmbulanceAppElement: {
        prototype: HTMLAmbulanceAppElement;
        new (): HTMLAmbulanceAppElement;
    };
    interface HTMLAppointmentSchedulerElement extends Components.AppointmentScheduler, HTMLStencilElement {
    }
    var HTMLAppointmentSchedulerElement: {
        prototype: HTMLAppointmentSchedulerElement;
        new (): HTMLAppointmentSchedulerElement;
    };
    interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {
    }
    var HTMLHomePageElement: {
        prototype: HTMLHomePageElement;
        new (): HTMLHomePageElement;
    };
    interface HTMLElementTagNameMap {
        "ambulance-app": HTMLAmbulanceAppElement;
        "appointment-scheduler": HTMLAppointmentSchedulerElement;
        "home-page": HTMLHomePageElement;
    }
}
declare namespace LocalJSX {
    interface AmbulanceApp {
    }
    interface AppointmentScheduler {
    }
    interface HomePage {
    }
    interface IntrinsicElements {
        "ambulance-app": AmbulanceApp;
        "appointment-scheduler": AppointmentScheduler;
        "home-page": HomePage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ambulance-app": LocalJSX.AmbulanceApp & JSXBase.HTMLAttributes<HTMLAmbulanceAppElement>;
            "appointment-scheduler": LocalJSX.AppointmentScheduler & JSXBase.HTMLAttributes<HTMLAppointmentSchedulerElement>;
            "home-page": LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
        }
    }
}
