kind: Service
apiVersion: v1
metadata:
  name: xcastven-xkilian-openapi-ui
spec:
  selector:
    pod: xcastven-xkilian-project-webapi-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
