openapi: 3.0.4
info:
  title: MediCal API
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
tags:
  - name: Auth
  - name: Appointments
  - name: Doctors
  - name: Patients
  - name: Medical History
  - name: Resources

paths:
  /auth/register:
    $ref: "./paths/auth_register.yaml"
  /auth/login:
    $ref: "./paths/auth_login.yaml"

  /patients/{patientId}:
    $ref: "./paths/patients_patientId.yaml"
  /patients/{patientId}/calendar:
    $ref: "./paths/patients_patientId_calendar.yaml"
  /patients/{patientId}/medical-history/files:
    $ref: "./paths/patients_medical_history.yaml"

  /doctors/{doctorId}:
    $ref: "./paths/doctors_doctorId.yaml"
  /doctors/{doctorId}/calendar:
    $ref: "./paths/patients_patientId_calendar.yaml"
  # /doctors/{doctorId}/timeslots:
  #   $ref: "./paths/doctors_doctorId_timeslots.yaml"
  # /appointments:
  #   $ref: "./paths/appointments.yaml"
  # /appointments/{appointmentId}/cancel:
  #   $ref: "./paths/appointments_appointmentId_cancel.yaml"
  # /appointments/{appointmentId}/reschedule:
  #   $ref: "./paths/appointments_appointmentId_reschedule.yaml"
  # /appointments/{appointmentId}/resources:
  #   $ref: "./paths/appointments_appointmentId_resources.yaml"
  # /appointments/{appointmentId}/decision:
  #   $ref: "./paths/appointments_appointmentId_decision.yaml"
  # /resources/available:
  #   $ref: "./paths/resources_available.yaml"
