name: BE CI

on:
  push:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/be-ci.yaml"
    tags:
      - "v1*"
  pull_request:
    branches: ["main"]
    paths:
      - "backend/**"
      - ".github/workflows/be-ci.yaml"

jobs:
  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            nesquiko/xcastven-xkilian-wac-be
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=branch,suffix={{date '.YYYYMMDD.HHmm'}}
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: dockerfile-be
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
