name: FE CI

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
    tags:
      - "v1*"
  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**"
      - ".github/workflows/fe-ci.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Bun.js
        uses: oven-sh/setup-bun@v2

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/bun.lockb') }}

      - name: Install Dependencies
        working-directory: frontend
        run: bun install --frozen-lockfile

      - name: Install Dependencies in API
        working-directory: api
        run: bun install --frozen-lockfile

      - name: Build
        working-directory: frontend
        run: bun run openapi

      - name: Build
        working-directory: frontend
        run: bun run build

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            nesquiko/xcastven-xkilian-wac-fe
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=branch,suffix={{date '.YYYYMMDD.HHmm'}}
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
